In [10]:
import pandas as pd
masses_data1=pd.read_csv("C://Users/ASUS/Downloads/MLCourse/mammographic_masses.data.txt", na_values=["?"],names=['bi-rads','age','shape','margin','density','serverty'])
masses_data1

bi-rads   age  shape  margin  density  serverty
0        5.0  67.0    3.0     5.0      3.0         1
1        4.0  43.0    1.0     1.0      NaN         1
2        5.0  58.0    4.0     5.0      3.0         1
3        4.0  28.0    1.0     1.0      3.0         0
4        5.0  74.0    1.0     5.0      NaN         1
..       ...   ...    ...     ...      ...       ...
956      4.0  47.0    2.0     1.0      3.0         0
957      4.0  56.0    4.0     5.0      3.0         1
958      4.0  64.0    4.0     5.0      3.0         0
959      5.0  66.0    4.0     5.0      3.0         1
960      4.0  62.0    3.0     3.0      3.0         0

[961 rows x 6 columns]

In [11]:
masses_data1.mean()

bi-rads      4.348279
age         55.487448
shape        2.721505
margin       2.796276
density      2.910734
serverty     0.463059
dtype: float64

In [12]:
masses_data1.std()

bi-rads      1.783031
age         14.480131
shape        1.242792
margin       1.566546
density      0.380444
serverty     0.498893
dtype: float64

In [13]:
masses_data1.describe()

bi-rads         age       shape      margin     density    serverty
count  959.000000  956.000000  930.000000  913.000000  885.000000  961.000000
mean     4.348279   55.487448    2.721505    2.796276    2.910734    0.463059
std      1.783031   14.480131    1.242792    1.566546    0.380444    0.498893
min      0.000000   18.000000    1.000000    1.000000    1.000000    0.000000
25%      4.000000   45.000000    2.000000    1.000000    3.000000    0.000000
50%      4.000000   57.000000    3.000000    3.000000    3.000000    0.000000
75%      5.000000   66.000000    4.000000    4.000000    3.000000    1.000000
max     55.000000   96.000000    4.000000    5.000000    4.000000    1.000000

In [14]:
masses_data=masses_data1.fillna(masses_data1.mean())
masses_data.isnull().sum()

bi-rads     0
age         0
shape       0
margin      0
density     0
serverty    0
dtype: int64

In [15]:
all_features= masses_data[['age','shape','margin','density']].values
all_features
all_classes=masses_data[['serverty']].values
feature_name=['age','shape','margin','density']
all_features

array([[67.        ,  3.        ,  5.        ,  3.        ],
       [43.        ,  1.        ,  1.        ,  2.91073446],
       [58.        ,  4.        ,  5.        ,  3.        ],
       ...,
       [64.        ,  4.        ,  5.        ,  3.        ],
       [66.        ,  4.        ,  5.        ,  3.        ],
       [62.        ,  3.        ,  3.        ,  3.        ]])

In [16]:
from sklearn import preprocessing

scaler=preprocessing.StandardScaler()
all_features_scaled= scaler.fit_transform(all_features)
all_features_scaled

array([[ 0.79755224,  0.22791465,  1.44403739,  0.24464071],
       [-0.86508983, -1.40884695, -1.17704837,  0.        ],
       [ 0.17406146,  1.04629545,  1.44403739,  0.24464071],
       ...,
       [ 0.58972198,  1.04629545,  1.44403739,  0.24464071],
       [ 0.72827549,  1.04629545,  1.44403739,  0.24464071],
       [ 0.45116848,  0.22791465,  0.13349451,  0.24464071]])

In [25]:
import numpy
from sklearn.model_selection import train_test_split
numpy.random.seed(1234)
(x_train,
x_test,
y_train,
y_test)=train_test_split(all_features,all_classes,train_size=0.91,random_state=1)

(87, 1)

In [34]:
from sklearn.tree import DecisionTreeClassifier
clf= DecisionTreeClassifier(random_state=100)

clf.fit(x_train,y_train)

DecisionTreeClassifier(random_state=100)

In [36]:
clf.score(x_test,y_test)

0.6781609195402298

In [37]:
from sklearn.svm import SVC
svm=SVC(C=10,kernel='linear')

In [38]:
svm.fit(x_train,y_train)

C:\Users\ASUS\.conda\envs\py3-TF2.0\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=10, kernel='linear')

In [39]:
svm.score(x_test,y_test)

0.8045977011494253

In [41]:
y_pred=svm.predict(x_test)

In [44]:
from sklearn.metrics import classification_report,confusion_matrix
print (confusion_matrix(y_test,y_pred))

[[43 11]
 [ 6 27]]


In [45]:
print (classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.88      0.80      0.83        54
           1       0.71      0.82      0.76        33

    accuracy                           0.80        87
   macro avg       0.79      0.81      0.80        87
weighted avg       0.81      0.80      0.81        87

